<?php

/**
* Inheritance: no
* Variants: no


Fields Summary:
- Name [input]
- ExternalName [input]
- Description [textarea]
- Photo [image]
- Modifiers [advancedManyToManyObjectRelation]
*/


return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'id' => '1',
   'name' => 'BasicItem',
   'description' => '',
   'creationDate' => 0,
   'modificationDate' => 1634771413,
   'userOwner' => 2,
   'userModification' => 2,
   'parentClass' => '',
   'implementsInterfaces' => '',
   'listingParentClass' => '',
   'useTraits' => '',
   'listingUseTraits' => '',
   'encryption' => false,
   'encryptedTables' => 
  array (
  ),
   'allowInherit' => false,
   'allowVariants' => false,
   'showVariants' => false,
   'fieldDefinitions' => 
  array (
  ),
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'fieldtype' => 'panel',
     'layout' => NULL,
     'border' => false,
     'name' => 'pimcore_root',
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => 0,
     'height' => 0,
     'collapsible' => false,
     'collapsed' => false,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'childs' => 
    array (
      0 => 
      Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel::__set_state(array(
         'fieldtype' => 'tabpanel',
         'border' => false,
         'tabPosition' => NULL,
         'name' => 'Layout',
         'type' => NULL,
         'region' => NULL,
         'title' => '',
         'width' => '',
         'height' => '',
         'collapsible' => false,
         'collapsed' => false,
         'bodyStyle' => '',
         'datatype' => 'layout',
         'permissions' => NULL,
         'childs' => 
        array (
          0 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Basic Data',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Basic Data',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'Name',
                 'title' => 'Name',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'ExternalName',
                 'title' => 'External Name',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              2 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state(array(
                 'fieldtype' => 'textarea',
                 'width' => '',
                 'height' => '',
                 'maxLength' => NULL,
                 'showCharCount' => false,
                 'excludeFromSearchIndex' => false,
                 'name' => 'Description',
                 'title' => 'Description',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
              3 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Image::__set_state(array(
                 'fieldtype' => 'image',
                 'name' => 'Photo',
                 'title' => 'Photo',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'width' => '',
                 'height' => '',
                 'uploadPath' => '/BasicItems',
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 100,
             'labelAlign' => 'left',
          )),
          1 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Modifiers',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Modifiers',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\AdvancedManyToManyObjectRelation::__set_state(array(
                 'allowedClassId' => 'ItemModifierGroup',
                 'visibleFields' => 'id,key',
                 'columns' => 
                array (
                  0 => 
                  array (
                    'type' => 'bool',
                    'position' => 1,
                    'key' => 'size',
                    'id' => 'extModel2355-1',
                    'value' => '',
                    'label' => 'size options',
                  ),
                  1 => 
                  array (
                    'type' => 'bool',
                    'position' => 2,
                    'key' => 'isExtra',
                    'id' => 'extModel2355-2',
                    'label' => 'isExtra',
                    'value' => '',
                  ),
                ),
                 'columnKeys' => 
                array (
                  0 => 'size',
                  1 => 'isExtra',
                ),
                 'fieldtype' => 'advancedManyToManyObjectRelation',
                 'enableBatchEdit' => false,
                 'allowMultipleAssignments' => false,
                 'visibleFieldDefinitions' => 
                array (
                ),
                 'width' => '',
                 'height' => '',
                 'maxItems' => '',
                 'relationType' => true,
                 'allowToCreateNewObject' => false,
                 'optimizedAdminLoading' => false,
                 'enableTextSelection' => false,
                 'classes' => 
                array (
                ),
                 'pathFormatterClass' => '',
                 'name' => 'Modifiers',
                 'title' => 'Modifiers',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 100,
             'labelAlign' => 'left',
          )),
        ),
         'locked' => false,
         'blockedVarsForExport' => 
        array (
        ),
      )),
    ),
     'locked' => false,
     'blockedVarsForExport' => 
    array (
    ),
     'icon' => NULL,
     'labelWidth' => 100,
     'labelAlign' => 'left',
  )),
   'icon' => '/bundles/pimcoreadmin/img/flat-color-icons/basic-item.svg',
   'previewUrl' => '',
   'group' => '',
   'showAppLoggerTab' => false,
   'linkGeneratorReference' => '',
   'previewGeneratorReference' => '',
   'compositeIndices' => 
  array (
  ),
   'generateTypeDeclarations' => true,
   'showFieldLookup' => false,
   'propertyVisibility' => 
  array (
    'grid' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
    'search' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
  ),
   'enableGridLocking' => false,
   'dao' => NULL,
   'blockedVarsForExport' => 
  array (
  ),
));
